spring:
  application:
    name: DEPARTMENT-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-register: true
    service-url:
      defaultZone: https://service-registry-demo.herokuapp.com/eureka/
#      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: department-micro-service.herokuapp.com
